#! /bin/bash
# ./up lts-14.27
# ./up nightly-2020-01-25
# ./up lts-15.11
git commit -am "fix";git push
ssh root@mega.quid2.org 'cd docker;git pull'
ssh root@mega.quid2.org 'df -h'
#ssh root@mega.quid2.org 'df -h;docker system prune;df -h'

# update basic stack image
#ssh root@mega.quid2.org "cd docker/stack;./mk"

ssh root@mega.quid2.org "cd docker/stack/lts;./mk $1"

#ssh root@mega.quid2.org "cd docker/386;./mk"
#ssh root@mega.quid2.org "cd docker/eta;./mk"

#ssh root@mega.quid2.org "cd docker/arm;./mk"
#ssh root@mega.quid2.org "cd docker/aarch64;./mk"

#ssh root@mega.quid2.org "cd docker/aarch64;docker build -t quid2/aarch64-ubuntu-cabal ."

# docker build -t quid2/aarch64-ubuntu-cabal . 
# docker build  --build-arg CACHE_DATE="$(date)" -t quid2/armv7l-ubuntu-cabal . 

